### ISSUE TITLE
Some missions are missing

### ISSUE THREAD

**Issue by endtransmission** [Grauenwolf/BrimstoneMissions#10]
Issue:
The missions for Gastral Tyrant and Thunder Warriors generate an error. Assumption here is that the data is missing for both

Steps to reproduce:
- Go to the All Missions page
- Scroll down to the end
- Click on the mission links under Thunder Warriors or Gastral Tyrant

Result:
- You see the message "Error.
An error occurred while processing your request."

**Comment by Grauenwolf** [comment]
That's really weird. I can't think why only those two are broken but the rest are still working

**Comment by Grauenwolf** [comment]
Fixed!

Thank you for bringing this to my attention.
